<a href="https://colab.research.google.com/github/ferjo04wk/INESDI_-Repositorio-Data-Science_ML_IA/blob/main/%5B01%5D%20-%20v2%20Preparaci%C3%B3n%20de%20datos%20y%20EDA/Transformacion_Ejercicio_4_transformacion_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Transformación - Ejercicio 4: transformacion_titanic.ipynb

En este ejercicio aprenderás cómo aplicar transformaciones básicas a las variables de un dataset para prepararlo para un modelo de machine learning.

Trabajaremos con el dataset clásico de Titanic y aplicaremos técnicas de normalización, estandarización y codificación de variables categóricas.

### Objetivos
- Aplicar escalado Min-Max y Z-score sobre variables numéricas.
- Realizar codificación one-hot y label encoding sobre variables categóricas.
- Identificar qué variables deben ser transformadas y cómo.

### Descripción del dataset
Usaremos el dataset de Titanic disponible públicamente. Contiene información de los pasajeros como edad, sexo, clase, tarifa pagada y si sobrevivieron o no.

In [1]:
# Importar librerías necesarias
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Cargar el dataset Titanic desde GitHub
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 1. Selección de variables para transformar

In [5]:
# Seleccionamos variables numéricas y categóricas relevantes
vars_numericas = df.select_dtypes(include= ['number']).columns
vars_categoricas = df.select_dtypes(include=['object']).columns

In [6]:
vars_numericas

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [7]:
# Visualizamos valores nulos
df.isnull().mean().sort_values(ascending=False) * 100

Cabin          77.104377
Age            19.865320
Embarked        0.224467
PassengerId     0.000000
Name            0.000000
Pclass          0.000000
Survived        0.000000
Sex             0.000000
Parch           0.000000
SibSp           0.000000
Fare            0.000000
Ticket          0.000000
dtype: float64

In [8]:
# Imputamos valores nulos antes de transformar
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Como Cabin tiene muchos valores nulos, lo deshechamos
df = df.drop("Cabin", axis = 1)

In [9]:
# Comprobamos que ya no quedan valores null
df.isnull().mean().sort_values(ascending=False) * 100

PassengerId    0.0
Survived       0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64

In [10]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C

### 2. Normalización (Min-Max Scaling)

In [11]:
# Aplicamos Min-Max Scaling a las variables numéricas
scaler_minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[vars_numericas] = scaler_minmax.fit_transform(df[vars_numericas])
df_minmax[vars_numericas].describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,0.500000,0.383838,0.654321,0.363679,0.065376,0.063599,0.062858
std,0.289162,0.486592,0.418036,0.163605,0.137843,0.134343,0.096995
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.250000,0.000000,0.500000,0.271174,0.000000,0.000000,0.015440
50%,0.500000,0.000000,1.000000,0.346569,0.000000,0.000000,0.028213
75%,0.750000,1.000000,1.000000,0.434531,0.125000,0.000000,0.060508
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### 3. Estandarización StandardScaler

In [12]:
# Aplicamos StandardScaler
scaler_std = StandardScaler()
df_std = df.copy()
df_std[vars_numericas] = scaler_std.fit_transform(df[vars_numericas])
df_std[vars_numericas].describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,8.910000e+02,8.910000e+02,8.910000e+02,8.910000e+02,8.910000e+02,8.910000e+02,8.910000e+02
mean,6.379733e-17,3.987333e-17,-8.772133e-17,2.272780e-16,4.386066e-17,5.382900e-17,3.987333e-18
std,1.000562e+00,1.000562e+00,1.000562e+00,1.000562e+00,1.000562e+00,1.000562e+00,1.000562e+00
min,-1.730108e+00,-7.892723e-01,-1.566107e+00,-2.224156e+00,-4.745452e-01,-4.736736e-01,-6.484217e-01
25%,-8.650540e-01,-7.892723e-01,-3.693648e-01,-5.657365e-01,-4.745452e-01,-4.736736e-01,-4.891482e-01
50%,0.000000e+00,-7.892723e-01,8.273772e-01,-1.046374e-01,-4.745452e-01,-4.736736e-01,-3.573909e-01
75%,8.650540e-01,1.266990e+00,8.273772e-01,4.333115e-01,4.327934e-01,-4.736736e-01,-2.424635e-02
max,1.730108e+00,1.266990e+00,8.273772e-01,3.891554e+00,6.784163e+00,6.974147e+00,9.667167e+00

### 4. Codificación de variables categóricas

In [13]:
# Label Encoding para 'Sex'
le = LabelEncoder()
df['Sex_encoded'] = le.fit_transform(df['Sex'])
df[['Sex', 'Sex_encoded']].head()

      Sex  Sex_encoded
0    male            1
1  female            0
2  female            0
3  female            0
4    male            1

In [14]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_encoded
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1

In [15]:
# One-Hot Encoding para 'Embarked'
df_encoded = pd.get_dummies(df, columns=['Embarked'])

df_encoded[['Embarked_S', 'Embarked_Q', 'Embarked_C']].head(5)

   Embarked_S  Embarked_Q  Embarked_C
0        True       False       False
1       False       False        True
2        True       False       False
3        True       False       False
4        True       False       False

In [16]:
df_encoded.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Sex_encoded,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,1,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,0,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,0,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,1,False,False,True

### Conclusión
Hemos aprendido a aplicar transformaciones básicas de preparación de datos:
- Escalado con MinMaxScaler y StandardScaler
- Codificación con LabelEncoder y One-Hot Encoding

Estas transformaciones son necesarias antes de alimentar modelos de machine learning que no pueden procesar variables categóricas o son sensibles a las escalas numéricas.